### ISSUE TITLE
Commands and buttons don't work

### ISSUE THREAD

**Issue by konstantin1722** [ruecat/ollama-telegram#32]
I noticed that the reset chat command doesn't work as well as the history command.

I get this when I try to use the Settings button:
```
INFO:aiogram.event:Update id=815284387 is handled. Duration 10558 ms by bot id=6697802571
ollama-telegram  | INFO:aiogram.event:Update id=815284388 is handled. Duration 151 ms by bot id=6697802571
ollama-telegram  | DEBUG:httpcore.connection:connect_tcp.started host='127.0.0.1' port=11434 local_address=None timeout=None socket_options=None
ollama-telegram  | DEBUG:httpcore.connection:connect_tcp.failed exception=ConnectError(ConnectionRefusedError(111, 'Connection refused'))
ollama-telegram  | INFO:aiogram.event:Update id=815284389 is not handled. Duration 3 ms by bot id=6697802571
ollama-telegram  | ERROR:aiogram.event:Cause exception while process update id=815284389 by bot id=6697802571
ollama-telegram  | ConnectError: [Errno 111] Connection refused
ollama-telegram  | Traceback (most recent call last):
ollama-telegram  |   File "/usr/local/lib/python3.12/site-packages/httpx/_transports/default.py", line 66, in map_httpcore_exceptions
ollama-telegram  |     yield
ollama-telegram  |   File "/usr/local/lib/python3.12/site-packages/httpx/_transports/default.py", line 228, in handle_request
ollama-telegram  |     resp = self._pool.handle_request(req)
ollama-telegram  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ollama-telegram  |   File "/usr/local/lib/python3.12/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
ollama-telegram  |     raise exc from None
ollama-telegram  |   File "/usr/local/lib/python3.12/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
ollama-telegram  |     response = connection.handle_request(
ollama-telegram  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^
ollama-telegram  |   File "/usr/local/lib/python3.12/site-packages/httpcore/_sync/connection.py", line 99, in handle_request
ollama-telegram  |     raise exc
ollama-telegram  |   File "/usr/local/lib/python3.12/site-packages/httpcore/_sync/connection.py", line 76, in handle_request
ollama-telegram  |     stream = self._connect(request)
ollama-telegram  |              ^^^^^^^^^^^^^^^^^^^^^^
ollama-telegram  |   File "/usr/local/lib/python3.12/site-packages/httpcore/_sync/connection.py", line 122, in _connect
ollama-telegram  |     stream = self._network_backend.connect_tcp(**kwargs)
ollama-telegram  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ollama-telegram  |   File "/usr/local/lib/python3.12/site-packages/httpcore/_backends/sync.py", line 205, in connect_tcp
ollama-telegram  |     with map_exceptions(exc_map):
ollama-telegram  |   File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__
ollama-telegram  |     self.gen.throw(value)
ollama-telegram  |   File "/usr/local/lib/python3.12/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
ollama-telegram  |     raise to_exc(exc) from exc
ollama-telegram  | httpcore.ConnectError: [Errno 111] Connection refused
ollama-telegram  | 
ollama-telegram  | The above exception was the direct cause of the following exception:
ollama-telegram  | 
ollama-telegram  | Traceback (most recent call last):
ollama-telegram  |   File "/usr/local/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
ollama-telegram  |     response = await self.feed_update(bot, update, **kwargs)
ollama-telegram  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ollama-telegram  |   File "/usr/local/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
ollama-telegram  |     response = await self.update.wrap_outer_middleware(
ollama-telegram  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ollama-telegram  |   File "/usr/local/lib/python3.12/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
ollama-telegram  |     return await handler(event, data)
ollama-telegram  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
ollama-telegram  |   File "/usr/local/lib/python3.12/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 27, in __call__
ollama-telegram  |     return await handler(event, data)
ollama-telegram  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
ollama-telegram  |   File "/usr/local/lib/python3.12/site-packages/aiogram/fsm/middleware.py", line 41, in __call__
ollama-telegram  |     return await handler(event, data)
ollama-telegram  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
ollama-telegram  |   File "/usr/local/lib/python3.12/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
ollama-telegram  |     return await wrapped_inner(event, kwargs)
ollama-telegram  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ollama-telegram  |   File "/usr/local/lib/python3.12/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
ollama-telegram  |     return await wrapped()
ollama-telegram  |            ^^^^^^^^^^^^^^^
ollama-telegram  |   File "/usr/local/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
ollama-telegram  |     return await self.propagate_event(update_type=update_type, event=event, **kwargs)
ollama-telegram  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ollama-telegram  |   File "/usr/local/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
ollama-telegram  |     return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
ollama-telegram  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ollama-telegram  |   File "/usr/local/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
ollama-telegram  |     return await self._propagate_event(
ollama-telegram  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ollama-telegram  |   File "/usr/local/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 136, in _propagate_event
ollama-telegram  |     response = await observer.trigger(event, **kwargs)
ollama-telegram  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ollama-telegram  |   File "/usr/local/lib/python3.12/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
ollama-telegram  |     return await wrapped_inner(event, kwargs)
ollama-telegram  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ollama-telegram  |   File "/usr/local/lib/python3.12/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
ollama-telegram  |     return await wrapped()
ollama-telegram  |            ^^^^^^^^^^^^^^^
ollama-telegram  |   File "/code/run.py", line 100, in modelmanager_callback_handler
ollama-telegram  |     models = ollama.list()["models"]
ollama-telegram  |              ^^^^^^^^^^^^^
ollama-telegram  |   File "/usr/local/lib/python3.12/site-packages/ollama/_client.py", line 313, in list
ollama-telegram  |     return self._request('GET', '/api/tags').json()
ollama-telegram  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ollama-telegram  |   File "/usr/local/lib/python3.12/site-packages/ollama/_client.py", line 53, in _request
ollama-telegram  |     response = self._client.request(method, url, **kwargs)
ollama-telegram  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ollama-telegram  |   File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 814, in request
ollama-telegram  |     return self.send(request, auth=auth, follow_redirects=follow_redirects)
ollama-telegram  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ollama-telegram  |   File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 901, in send
ollama-telegram  |     response = self._send_handling_auth(
ollama-telegram  |                ^^^^^^^^^^^^^^^^^^^^^^^^^
ollama-telegram  |   File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 929, in _send_handling_auth
ollama-telegram  |     response = self._send_handling_redirects(
ollama-telegram  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ollama-telegram  |   File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 966, in _send_handling_redirects
ollama-telegram  |     response = self._send_single_request(request)
ollama-telegram  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ollama-telegram  |   File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 1002, in _send_single_request
ollama-telegram  |     response = transport.handle_request(request)
ollama-telegram  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ollama-telegram  |   File "/usr/local/lib/python3.12/site-packages/httpx/_transports/default.py", line 227, in handle_request
ollama-telegram  |     with map_httpcore_exceptions():
ollama-telegram  |   File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__
ollama-telegram  |     self.gen.throw(value)
ollama-telegram  |   File "/usr/local/lib/python3.12/site-packages/httpx/_transports/default.py", line 83, in map_httpcore_exceptions
ollama-telegram  |     raise mapped_exc(message) from exc
ollama-telegram  | httpx.ConnectError: [Errno 111] Connection refused
```

I get this when I try to use the Information button:
```
ollama-telegram  | INFO:aiogram.event:Update id=815284392 is not handled. Duration 2 ms by bot id=6697802571
ollama-telegram  | ERROR:aiogram.event:Cause exception while process update id=815284392 by bot id=6697802571
ollama-telegram  | AttributeError: 'CallbackQuery' object has no attribute 'chat'
ollama-telegram  | Traceback (most recent call last):
ollama-telegram  |   File "/usr/local/lib/python3.12/site-packages/pydantic/main.py", line 753, in __getattr__
ollama-telegram  |     return pydantic_extra[item]
ollama-telegram  |            ~~~~~~~~~~~~~~^^^^^^
ollama-telegram  | KeyError: 'chat'
ollama-telegram  | 
ollama-telegram  | The above exception was the direct cause of the following exception:
ollama-telegram  | 
ollama-telegram  | Traceback (most recent call last):
ollama-telegram  |   File "/usr/local/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
ollama-telegram  |     response = await self.feed_update(bot, update, **kwargs)
ollama-telegram  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ollama-telegram  |   File "/usr/local/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
ollama-telegram  |     response = await self.update.wrap_outer_middleware(
ollama-telegram  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ollama-telegram  |   File "/usr/local/lib/python3.12/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
ollama-telegram  |     return await handler(event, data)
ollama-telegram  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
ollama-telegram  |   File "/usr/local/lib/python3.12/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 27, in __call__
ollama-telegram  |     return await handler(event, data)
ollama-telegram  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
ollama-telegram  |   File "/usr/local/lib/python3.12/site-packages/aiogram/fsm/middleware.py", line 41, in __call__
ollama-telegram  |     return await handler(event, data)
ollama-telegram  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
ollama-telegram  |   File "/usr/local/lib/python3.12/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
ollama-telegram  |     return await wrapped_inner(event, kwargs)
ollama-telegram  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ollama-telegram  |   File "/usr/local/lib/python3.12/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
ollama-telegram  |     return await wrapped()
ollama-telegram  |            ^^^^^^^^^^^^^^^
ollama-telegram  |   File "/usr/local/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
ollama-telegram  |     return await self.propagate_event(update_type=update_type, event=event, **kwargs)
ollama-telegram  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ollama-telegram  |   File "/usr/local/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
ollama-telegram  |     return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
ollama-telegram  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ollama-telegram  |   File "/usr/local/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
ollama-telegram  |     return await self._propagate_event(
ollama-telegram  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ollama-telegram  |   File "/usr/local/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 136, in _propagate_event
ollama-telegram  |     response = await observer.trigger(event, **kwargs)
ollama-telegram  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ollama-telegram  |   File "/usr/local/lib/python3.12/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
ollama-telegram  |     return await wrapped_inner(event, kwargs)
ollama-telegram  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ollama-telegram  |   File "/usr/local/lib/python3.12/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
ollama-telegram  |     return await wrapped()
ollama-telegram  |            ^^^^^^^^^^^^^^^
ollama-telegram  |   File "/code/func/functions.py", line 73, in wrapper
ollama-telegram  |     if message and message.chat.type in ["supergroup", "group"]:
ollama-telegram  |                    ^^^^^^^^^^^^
ollama-telegram  |   File "/usr/local/lib/python3.12/site-packages/pydantic/main.py", line 755, in __getattr__
ollama-telegram  |     raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}') from exc
ollama-telegram  | AttributeError: 'CallbackQuery' object has no attribute 'chat'
```

I have ollama running outside of the docker container, the chat itself works.

**Comment by ruecat** [comment]
We are aware of this problem. 
Will be fixed soon

**Comment by ruecat** [comment]
It's connected with ollama library, we will rollback 2 commits

**Comment by frankfnord** [comment]
Hi, I see the same issue. Have ollama running as a docker container outside of ollama-telegram. should it already be fixed with your rollback 2 days ago?
