### ISSUE TITLE
Bot won't respond to @ in group "Something went wrong."

### ISSUE THREAD

**Issue by lediszep** [ruecat/ollama-telegram#50]
```
INFO:aiogram.event:Update id=692857612 is handled. Duration 1914 ms by bot id=7078882923
INFO:root:[OllamaAPI]: Processing 'hi' for Shaun Nicholson
-----
[OllamaAPI-ERR] CAUGHT FAULT!
Traceback (most recent call last):
  File "/code/run.py", line 237, in ollama_request
    if await handle_response(message, response_data, full_response):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/run.py", line 194, in handle_response
    await send_response(message, text)
  File "/code/run.py", line 210, in send_response
    await bot.edit_message_text(
  File "/usr/local/lib/python3.12/site-packages/aiogram/client/bot.py", line 1475, in edit_message_text
    return await self(call, request_timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiogram/client/bot.py", line 432, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiogram/client/session/base.py", line 257, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiogram/client/session/aiohttp.py", line 179, in make_request
    response = self.check_response(
               ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiogram/client/session/base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: message can't be edited

-----
INFO:aiogram.event:Update id=692857613 is handled. Duration 1881 ms by bot id=7078882923
```

**Comment by ruecat** [comment]
I'm aware of this problem, fix soon

**Comment by lediszep** [comment]
When fixed:

In USER_IDS: we put the group id only? and that allows everyone in the group to @ the bot?
