### ISSUE TITLE
Testing in group

### ISSUE THREAD

**Issue by Jake401-latest** [ruecat/ollama-telegram#58]
Im trying to use the bot in a group by using @bot [message]

but in report this:

**-----
[OllamaAPI-ERR] CAUGHT FAULT!
Traceback (most recent call last):
  File "/home/mobley/Documents/Software/ollama-telegram-bot/bot/run.py", line 236, in ollama_request
    if await handle_response(message, response_data, full_response):
  File "/home/mobley/Documents/Software/ollama-telegram-bot/bot/run.py", line 193, in handle_response
    await send_response(message, text)
  File "/home/mobley/Documents/Software/ollama-telegram-bot/bot/run.py", line 209, in send_response
    await bot.edit_message_text(
  File "/home/mobley/.local/lib/python3.10/site-packages/aiogram/client/bot.py", line 1475, in edit_message_text
    return await self(call, request_timeout=request_timeout)
  File "/home/mobley/.local/lib/python3.10/site-packages/aiogram/client/bot.py", line 432, in __call__
    return await self.session(self, method, timeout=request_timeout)
  File "/home/mobley/.local/lib/python3.10/site-packages/aiogram/client/session/base.py", line 257, in __call__
    return cast(TelegramType, await middleware(bot, method))
  File "/home/mobley/.local/lib/python3.10/site-packages/aiogram/client/session/aiohttp.py", line 179, in make_request
    response = self.check_response(
  File "/home/mobley/.local/lib/python3.10/site-packages/aiogram/client/session/base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: message can't be edited

-----
**

**Comment by bschwab** [comment]
i did a pull as of 13f530f and it seems to be working for me
can you try pulling latest?
