### ISSUE TITLE
Error in latest docker image: SELECT id FROM users

### ISSUE THREAD

**Issue by zahidhanif** [ruecat/ollama-telegram#69]
I am getting an error with the latest docker image and the logs say it's having problem with running queries such as SELECT id FROM users. The latest docker image was published earlier today

**Comment by zahidhanif** [comment]
Here is the full error:
Traceback (most recent call last):                                                                        │
│     File "/code/run.py", line 6, in <module>                                                                │
│       from func.interactions import *                                                                       │
│     File "/code/func/interactions.py", line 68, in <module>                                                 │
│       allowed_ids = load_allowed_ids_from_db()                                                              │
│                     ^^^^^^^^^^^^^^^^^^^^^^^^^^                                                              │
│     File "/code/func/interactions.py", line 63, in load_allowed_ids_from_db                                 │
│       c.execute("SELECT id FROM users")                                                                     │
│   sqlite3.OperationalError: no such table: users

**Comment by eboye** [comment]
I just tried it and this came up. Same error.

**Comment by meligera** [comment]
I just executed part where it creates db manually:

```python
import sqlite3
def init_db():
    conn = sqlite3.connect('users.db')
    c = conn.cursor()
    c.execute('''CREATE TABLE IF NOT EXISTS users
                 (id INTEGER PRIMARY KEY, name TEXT)''')
    c.execute('''CREATE TABLE IF NOT EXISTS chats
                 (id INTEGER PRIMARY KEY AUTOINCREMENT,
                  user_id INTEGER,
                  role TEXT,
                  content TEXT,
                  timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
                  FOREIGN KEY (user_id) REFERENCES users(id))''')
    conn.commit()
    conn.close()
   
init_db()
```

**Comment by Justieku** [comment]
> I executed part where it creates db manually, and it started normally after:
> 
> ```python
> import sqlite3
> def init_db():
>     conn = sqlite3.connect('users.db')
>     c = conn.cursor()
>     c.execute('''CREATE TABLE IF NOT EXISTS users
>                  (id INTEGER PRIMARY KEY, name TEXT)''')
>     c.execute('''CREATE TABLE IF NOT EXISTS chats
>                  (id INTEGER PRIMARY KEY AUTOINCREMENT,
>                   user_id INTEGER,
>                   role TEXT,
>                   content TEXT,
>                   timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
>                   FOREIGN KEY (user_id) REFERENCES users(id))''')
>     conn.commit()
>     conn.close()
>    
> init_db()
> ```

Thank you! Worked for me

**Comment by zahidhanif** [comment]
I am using the docker image, so will this be included in the docker build?

**Comment by eboye** [comment]
@zahidhanif it's included, but it doesn't run for some reason.

**Comment by aliasx** [comment]
- Clone Repository
- Copy this code  from `run.py`:
```
    c = conn.cursor()
    c.execute('''CREATE TABLE IF NOT EXISTS users
                 (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT)''')
    c.execute('''CREATE TABLE IF NOT EXISTS chats
                 (id INTEGER PRIMARY KEY AUTOINCREMENT,
                  user_id INTEGER,
                  role TEXT,
                  content TEXT,
                  timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
                  FOREIGN KEY (user_id) REFERENCES users(id))''')
    conn.commit()

```
to `interactions.py` after:
```
def load_allowed_ids_from_db():
    conn = sqlite3.connect('users.db')
``` 
- Build and run `docker compose up --build -d`

**Comment by eboye** [comment]
I've mapped the users.db volume in yml and made my own empty db, it worked that way.

**Comment by zahidhanif** [comment]
> I've mapped the users.db volume in yml and made my own empty db, it worked that way.

Can you please send me an example?

**Comment by eboye** [comment]
Here's the empty users.db (just extract it to bot folder):
[users.zip](https://github.com/user-attachments/files/17174841/users.zip)


Docker compose I'm using:

```yaml
version: '3.8'
services:
  ollama-telegram:
    container_name: ollama-telegram
    image: ruecat/ollama-telegram
    restart: on-failure
    env_file:
      - ./.env
    volumes:
      - ./users.db:/code/users.db

  ollama-server:
    image: ollama/ollama
    container_name: ollama-server
    volumes:
      - ./ollama:/root/.ollama
    restart: always
    ports:
      - '11434:11434'
```

Once started, I had to execute ollama pull on the ollama-server container like this:

```bash
docker exec -it [container_id] ollama pull llama3.2:1b
```

replace [container_id] with container id from ``docker ps`` command of the ollama-server.

And the .env file looks like this:

```env
TOKEN=
ADMIN_IDS=
USER_IDS=
ALLOW_ALL_USERS_IN_GROUPS=1
INITMODEL=llama3.2:1b
TIMEOUT=3000

# UNCOMMENT ONE OF THE FOLLOWING LINES:
# OLLAMA_BASE_URL=localhost # to run ollama without docker, using run.py
OLLAMA_BASE_URL=ollama-server # to run ollama in a docker container 
# OLLAMA_BASE_URL=host.docker.internal # to run ollama locally

OLLAMA_HOST=${OLLAMA_BASE_URL}

# Log level
# https://docs.python.org/3/library/logging.html#logging-levels
LOG_LEVEL=DEBUG
```

**Comment by zahidhanif** [comment]
> Here's the empty users.db (just extract it to root folder of the project): [users.zip](https://github.com/user-attachments/files/17174841/users.zip)
> 
> Docker compose I'm using:
> 
> ```yaml
> version: '3.8'
> services:
>   ollama-telegram:
>     container_name: ollama-telegram
>     image: ruecat/ollama-telegram
>     restart: on-failure
>     env_file:
>       - ./.env
>     volumes:
>       - ./users.db:/code/users.db
> 
>   ollama-server:
>     image: ollama/ollama
>     container_name: ollama-server
>     volumes:
>       - ./ollama:/root/.ollama
>     restart: always
>     ports:
>       - '11434:11434'
> ```
> 
> Once started, I had to execute ollama pull on the ollama-server container like this:
> 
> ```shell
> docker exec -it [container_id] ollama pull llama3.2:1b
> ```
> 
> replace [container_id] with container id from `docker ps` command of the ollama-server.
> 
> And the .env file looks like this:
> 
> ```dotenv
> TOKEN=
> ADMIN_IDS=
> USER_IDS=
> ALLOW_ALL_USERS_IN_GROUPS=1
> INITMODEL=llama3.2:1b
> TIMEOUT=3000
> 
> # UNCOMMENT ONE OF THE FOLLOWING LINES:
> # OLLAMA_BASE_URL=localhost # to run ollama without docker, using run.py
> OLLAMA_BASE_URL=ollama-server # to run ollama in a docker container 
> # OLLAMA_BASE_URL=host.docker.internal # to run ollama locally
> 
> OLLAMA_HOST=${OLLAMA_BASE_URL}
> 
> # Log level
> # https://docs.python.org/3/library/logging.html#logging-levels
> LOG_LEVEL=DEBUG
> ```

Thanks, that's worked for me

**Comment by hhenne1** [comment]
hm..  i'm still getting this after the latest update:
`Traceback (most recent call last):
  File "/code/run.py", line 6, in <module>
    from func.interactions import *
  File "/code/func/interactions.py", line 68, in <module>
    allowed_ids = load_allowed_ids_from_db()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/func/interactions.py", line 63, in load_allowed_ids_from_db
    c.execute("SELECT id FROM users")
sqlite3.OperationalError: no such table: users`

mapping the db-file just change the error message to something like "can't read users.db"..

**Comment by eboye** [comment]
@hhenne1 sounds like permission issue to me. Does docker user has rw access to that file?

**Comment by hhenne1** [comment]
oh yea.. im dumb.. my bad, sry.. had a typo in the mount path.. should have realized that docker was mounting an empty folder instead of the file..

**Comment by qdii** [comment]
May be related to the comment I left in https://github.com/ruecat/ollama-telegram/pull/61/commits/d3fb767f384b682737ee7cfb537f90bc980d0a47

**Comment by qdii** [comment]
Unfortunately, the only existing Docker image is tagged `latest` (https://hub.docker.com/r/ruecat/ollama-telegram/tags?ordering=-last_updated), so there is no possibility to rollback.

**Comment by haydonryan** [comment]
I just tried to install this from scratch... I'm still getting the errors:

```
$ docker-compose logs -f
ollama-telegram  | Traceback (most recent call last):
ollama-telegram  |   File "/code/run.py", line 6, in <module>
ollama-telegram  |     from func.interactions import *
ollama-telegram  |   File "/code/func/interactions.py", line 68, in <module>
ollama-telegram  |     allowed_ids = load_allowed_ids_from_db()
ollama-telegram  |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
ollama-telegram  |   File "/code/func/interactions.py", line 63, in load_allowed_ids_from_db
ollama-telegram  |     c.execute("SELECT id FROM users")
ollama-telegram  | sqlite3.OperationalError: no such table: users
ollama-telegram  | Traceback (most recent call last):
ollama-telegram  |   File "/code/run.py", line 6, in <module>
ollama-telegram  |     from func.interactions import *
ollama-telegram  |   File "/code/func/interactions.py", line 68, in <module>
ollama-telegram  |     allowed_ids = load_allowed_ids_from_db()
ollama-telegram  |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
ollama-telegram  |   File "/code/func/interactions.py", line 63, in load_allowed_ids_from_db
ollama-telegram  |     c.execute("SELECT id FROM users")
ollama-telegram  | sqlite3.OperationalError: no such table: users
ollama-telegram  | Traceback (most recent call last):
ollama-telegram  |   File "/code/run.py", line 6, in <module>
ollama-telegram  |     from func.interactions import *
ollama-telegram  |   File "/code/func/interactions.py", line 68, in <module>
ollama-telegram  |     allowed_ids = load_allowed_ids_from_db()
ollama-telegram  |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
ollama-telegram  |   File "/code/func/interactions.py", line 63, in load_allowed_ids_from_db
```
Has the changes been pushed to docker hub?

**Comment by GDGooD** [comment]
Here is hotfix patch based on @fredix solution.
Use with git apply `hotfix-db-users.patch.txt`
[hotfix-db-users.patch.txt](https://github.com/user-attachments/files/17525738/hotfix-db-users.patch.txt)
